# Generated by Django 3.0.1 on 2020-01-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_wine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wine',
            name='is_in_home',
            field=models.CharField(max_length=100),
        ),
    ]
